apiVersion: v1
kind: Service
metadata:
  name: management-{{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: management
spec:
  selector:
    app: {{ template "name" . }}
    release: "{{ .Release.Name }}"
    component: management
  ports:
    - name: management-port
      port: {{ .Values.management.app.service.port }}
      targetPort: {{ .Values.management.app.service.port }}
    - name: metrics-port
      port: {{ .Values.management.app.service.metricsPort }}
      targetPort: {{ .Values.management.app.service.metricsPort }}