apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: management-pv-claim
  namespace: redirectory
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard