apiVersion: v1
kind: Service
metadata:
  name: redirectory-management
  labels:
    app: redirectory
    component: management
spec:
  selector:
    app: redirectory-management
  ports:
    - name: management-port
      port: 8001
      targetPort: 8001
    - name: metrics-port
      port: 8002
      targetPort: 8002
