apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirectory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirectory-management
  template:
    metadata:
      labels:
        app: redirectory-management
    spec:
      imagePullSecrets:
        - name: kumina-registry
      containers:
        - name: redirectory-management
          image: registry.kumina.nl/kumina/redirectory-management:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8001
              name: normal
            - containerPort: 8002
              name: metrics
          livenessProbe:
            httpGet:
              path: /status/health_check
              port: normal
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /status/readiness_check
              port: normal
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: REDIRECTORY_CONFIG_DIR
              value: "/redirectory_config"
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: management-configuration
              mountPath: /redirectory_config
            - name: management-redirectory
              mountPath: /redirectory_data
      serviceAccountName: redirectory
      volumes:
        - name: management-configuration
          configMap:
            name: redirectory-management
        - name: management-redirectory
          persistentVolumeClaim:
            claimName: management-pv-claim

