apiVersion: v1
kind: PersistentVolume
metadata:
  name: management-pv
  labels:
    type: redirectory-management
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda1/data/redirectory"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: management-pv-claim
spec:
  selector:
    matchLabels:
      type: redirectory-management
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
