apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: prom
  name: redirectory-management
  namespace: infra
spec:
  endpoints:
    - interval: 30s
      port: metrics-port
  jobLabel: app
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: redirectory
      component: management
