apiVersion: v1
kind: ServiceAccount
metadata:
  name: redirectory
  namespace: redirectory
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: redirectory
  namespace: redirectory
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: redirectory
subjects:
- kind: ServiceAccount
  name: redirectory
  namespace: redirectory
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: redirectory
  namespace: redirectory
rules:
- apiGroups: [""]
  resources:
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
