apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirectory-worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: redirectory-worker
  template:
    metadata:
      labels:
        app: redirectory-worker
    spec:
      containers:
        - name: redirectory-worker
          image: redirectory_worker:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8001
              name: normal
            - containerPort: 8002
              name: metrics
          livenessProbe:
            httpGet:
              path: /status/health_check
              port: normal
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /status/readiness_check
              port: normal
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: REDIRECTORY_CONFIG_DIR
              value: "/redirectory_config"
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: worker-configuration
              mountPath: /redirectory_config
      serviceAccountName: redirectory
      volumes:
        - name: worker-configuration
          configMap:
            name: redirectory-worker
